# Generated by Django 5.1.4 on 2026-05-21 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('state', models.CharField(max_length=80)),
                ('popular', models.BooleanField(default=False)),
                ('car_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ('-popular', 'name'),
            },
        ),
    ]
