# Generated by Django 5.1.4 on 2026-05-21 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_title', models.CharField(max_length=200)),
                ('listing_price', models.CharField(blank=True, default='', max_length=40)),
                ('buyer_name', models.CharField(max_length=120)),
                ('buyer_phone', models.CharField(max_length=15)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('seller_name', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Call'), ('form', 'Form'), ('chat', 'Chat')], default='form', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('responded', 'Responded'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ('-created_at',),
            },
        ),
    ]
