# Generated by Django 5.1.4 on 2026-06-06 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_testdrivebooking_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(db_index=True, max_length=80)),
                ('loan_partner', models.CharField(db_index=True, max_length=80)),
                ('full_name', models.CharField(max_length=120)),
                ('mobile', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=80)),
                ('monthly_income', models.PositiveIntegerField()),
                ('employment_type', models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self-Employed')], default='salaried', max_length=20)),
                ('car_budget', models.CharField(blank=True, default='', max_length=80)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan inquiry',
                'verbose_name_plural': 'Loan inquiries',
                'ordering': ('-created_at',),
            },
        ),
    ]
