# Generated by Django 5.1.4 on 2026-06-15 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_loaninquiry'),
        ('listings', '0004_listingboostorder_base_inr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_title', models.CharField(max_length=200)),
                ('listing_price', models.CharField(blank=True, default='', max_length=40)),
                ('viewer_name', models.CharField(blank=True, default='', max_length=120)),
                ('viewer_phone', models.CharField(blank=True, default='', max_length=15)),
                ('viewer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('seller_name', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_leads', to='listings.listing')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing view lead',
                'verbose_name_plural': 'Listing view leads',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['seller', '-updated_at'], name='inquiries_l_seller__1b3b68_idx'), models.Index(fields=['listing', 'viewer'], name='inquiries_l_listing_9332d0_idx')],
            },
        ),
    ]
