# Generated by Django 5.1.4 on 2026-05-21 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=120)),
                ('seller_phone', models.CharField(max_length=15)),
                ('seller_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(db_index=True, max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('variant', models.CharField(blank=True, default='', max_length=120)),
                ('year', models.PositiveIntegerField()),
                ('price_label', models.CharField(max_length=40)),
                ('price_inr', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('kms', models.PositiveIntegerField(default=0)),
                ('fuel', models.CharField(max_length=24)),
                ('transmission', models.CharField(max_length=24)),
                ('owners', models.CharField(max_length=32)),
                ('ownership', models.CharField(blank=True, default='', max_length=32)),
                ('body_type', models.CharField(blank=True, default='', max_length=32)),
                ('color', models.CharField(blank=True, default='', max_length=32)),
                ('seats', models.PositiveSmallIntegerField(default=5)),
                ('engine_cc', models.CharField(blank=True, default='', max_length=16)),
                ('mileage', models.CharField(blank=True, default='', max_length=24)),
                ('registration_month', models.CharField(blank=True, default='', max_length=16)),
                ('reg_number', models.CharField(blank=True, default='', max_length=32)),
                ('insurance', models.CharField(blank=True, default='', max_length=64)),
                ('location', models.CharField(db_index=True, max_length=80)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list)),
                ('cover_image', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('draft', 'Draft')], default='active', max_length=10)),
                ('moderation', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=10)),
                ('rejected_reason', models.TextField(blank=True, default='')),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, default='')),
                ('whatsapp', models.BooleanField(default=True)),
                ('is_seed', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('inquiries_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
