# Generated by Django 5.1.4 on 2026-06-04 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='boosted_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ListingBoostOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package', models.CharField(db_index=True, max_length=32)),
                ('duration_days', models.PositiveSmallIntegerField(default=0)),
                ('amount_inr', models.PositiveIntegerField()),
                ('razorpay_order_id', models.CharField(max_length=120, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=120)),
                ('receipt', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='created', max_length=12)),
                ('boosted_until', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_orders', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_boost_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='listings_li_user_id_beb5b7_idx'), models.Index(fields=['listing', 'status'], name='listings_li_listing_d53c81_idx')],
            },
        ),
    ]
