# Generated by Django 5.1.4 on 2026-06-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_boosted_until_listingboostorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingboostorder',
            name='base_inr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listingboostorder',
            name='customer_gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='listingboostorder',
            name='gst_inr',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
