# Generated by Django 5.1.4 on 2026-05-21 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('listing-approved', 'Listing approved'), ('listing-rejected', 'Listing rejected'), ('listing-featured', 'Listing featured'), ('listing-unfeatured', 'Listing unfeatured'), ('listing-blocked', 'Listing blocked'), ('listing-deleted', 'Listing deleted'), ('user-blocked', 'User blocked'), ('user-unblocked', 'User unblocked'), ('user-verified', 'User verified'), ('admin-login', 'Admin login'), ('settings-updated', 'Settings updated')], max_length=32)),
                ('message', models.TextField()),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('super-admin', 'Super admin'), ('moderator', 'Moderator'), ('support', 'Support')], default='moderator', max_length=20)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('auto_approve_listings', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('max_photos_per_listing', models.PositiveSmallIntegerField(default=12)),
                ('min_listing_price', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('max_listing_price', models.DecimalField(decimal_places=2, default=50000000, max_digits=12)),
                ('blocked_keywords', models.JSONField(blank=True, default=list)),
                ('support_email', models.EmailField(default='support@oldcarbazar.com', max_length=254)),
                ('support_phone', models.CharField(default='+91 98765 43210', max_length=32)),
                ('brand_color', models.CharField(default='#f75d34', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App settings',
                'verbose_name_plural': 'App settings',
            },
        ),
    ]
